import type { Metadata } from "next";
import Link from "next/link";
import { CONTACT_EMAIL, SITE_NAME } from "../../../lib/site";

export const metadata: Metadata = {
  title: `Terms & Conditions · ${SITE_NAME}`,
  description: "The terms that govern your use of Chessmasters.",
};

export default function TermsPage() {
  return (
    <>
      <h1>Terms &amp; Conditions</h1>
      <p className="legal-updated">Last updated: September 30, 2026</p>
      <p>
        These terms describe the {SITE_NAME} service. By creating an account or
        using the service, you agree to them.
      </p>

      <h2>The service</h2>
      <p>
        {SITE_NAME} analyzes chess games you submit from Lichess or Chess.com and
        generates an AI-written coaching report, including engine notes and
        training resources. The service is provided for personal chess training
        and entertainment.
      </p>

      <h2>AI-generated content</h2>
      <p>
        Reports are generated by an AI model from your game and engine data.
        They can contain mistakes or omissions. Treat them as study suggestions,
        not professional advice, and verify critical lines with an engine.
      </p>

      <h2>Your account</h2>
      <ul>
        <li>You are responsible for keeping access to your login email secure.</li>
        <li>You must be old enough to hold a payment method to subscribe.</li>
        <li>You can stop using the service at any time.</li>
      </ul>

      <h2>Acceptable use</h2>
      <ul>
        <li>Do not abuse, overload, or attempt to disrupt the service.</li>
        <li>Do not resell reports or access to the service.</li>
        <li>Only submit games and accounts you have the right to use.</li>
      </ul>

      <h2>Subscriptions &amp; billing</h2>
      <p>
        The paid plan is ₹399 per month, billed through Razorpay, and renews
        automatically until cancelled. You can pause or cancel any time from the{" "}
        <Link href="/subscription">Subscription page</Link>. See the{" "}
        <Link href="/refund">Refund &amp; Cancellation Policy</Link> for details.
      </p>

      <h2>Availability &amp; liability</h2>
      <p>
        The service is provided &ldquo;as is&rdquo; without warranties. To the
        maximum extent allowed by law, {SITE_NAME} is not liable for indirect or
        consequential damages arising from your use of the service.
      </p>

      <h2>Third-party services</h2>
      <p>
        {SITE_NAME} is not affiliated with Lichess or Chess.com. Your use of
        those platforms is governed by their own terms.
      </p>

      <h2>Changes</h2>
      <p>
        We may update these terms. Continued use of the service after an update
        means you accept the new terms.
      </p>

      <h2>Contact</h2>
      <p>
        Questions? Email{" "}
        <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.
      </p>
    </>
  );
}
